name: nt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  card_swiper: ^2.0.4
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.18.0
  mask_text_input_formatter: ^2.4.0

  credit_card_scanner: ^1.0.5
  uuid: ^3.0.7
  fluttertoast: ^8.1.2
  device_info_plus: ^8.0.0
  meta: ^1.8.0
  path_provider: ^2.0.12
  sqflite: ^2.2.4+1
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
